### ISSUE TITLE
OpenCL clBuildProgram intermittent segfault on Intel HD 520 on Ubuntu Linux 19.10 with intel-graphics-compiler version igc-1.0.3041

### ISSUE THREAD

**Issue by thenumbernine** [intel/intel-graphics-compiler#124]
Hello, the same issue as I reported before here ( https://github.com/intel/intel-graphics-compiler/issues/115 ) is still producing a segfault, but now with a different call stack when it crashes.

I am testing this on the latest intel-opencl-icd for ubuntu, which at present is 20.02.15268-1, which uses intel-graphics-compiler igc-1.0.3041, but could have been present before that.

The following OpenCL code intermittently causes a segfault in clBuildProgram:

```
#if	1	//double fails
#pragma OPENCL EXTENSION cl_khr_fp64 : enable
typedef double real;
#else	//float seems to work
typedef float real;
#endif

typedef union {
	real s[3];
	//commenting out the other union has no effect on preventing the intermittent crash
	struct { real x, y, z; };
} real3;

real3 real3_zero() {
	//intermittently crashes the compiler
	return (real3){.s={0,0,0}};
	//works 
	//return (real3){.x=0, .y=0, .z=0};
}

kernel void addSource() {
	//produces a crash depending on the body of real3_zero()
	real3 conn12 = real3_zero();
	//works -- produces no compiler crash
	//real3 conn12 = (real3){.s={0,0,0}};
	//works -- produces no compiler crash
	//real3 conn12 = (real3){.x=0, .y=0, .z=0};
}
```

Using float instead of double seems to prevent the crash.

The new GDB stack trace upon segfault is:

```
(gdb) run
Starting program: /home/chris/Projects/cpp/IntelGPUIsolatedBug2/dist/linux/debug/IntelGPUIsolatedBug2 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff74dc700 (LWP 27810)]

Thread 1 "IntelGPUIsolate" received signal SIGSEGV, Segmentation fault.
0x00007fffec988332 in llvm::ValueHandleBase::AddToUseList() () from /lib/x86_64-linux-gnu/libLLVM-9.so.1
(gdb) bt
#0  0x00007fffec988332 in llvm::ValueHandleBase::AddToUseList() () from /lib/x86_64-linux-gnu/libLLVM-9.so.1
#1  0x00007fffed057efe in ?? () from /lib/x86_64-linux-gnu/libLLVM-9.so.1
#2  0x00007fffed058f57 in ?? () from /lib/x86_64-linux-gnu/libLLVM-9.so.1
#3  0x00007fffed058ebd in llvm::ValueMapper::remapInstruction(llvm::Instruction&) () from /lib/x86_64-linux-gnu/libLLVM-9.so.1
#4  0x00007fffecf9a9a6 in ?? () from /lib/x86_64-linux-gnu/libLLVM-9.so.1
#5  0x00007fffecf98fbc in llvm::CloneAndPruneIntoFromInst(llvm::Function*, llvm::Function const*, llvm::Instruction const*, llvm::ValueMap<llvm::Value const*, llvm::WeakTrackingVH, llvm::ValueMapConfig<llvm::Value const*, llvm::sys::SmartMutex<false> > >&, bool, llvm::SmallVectorImpl<llvm::ReturnInst*>&, char const*, llvm::ClonedCodeInfo*) () from /lib/x86_64-linux-gnu/libLLVM-9.so.1
#6  0x00007fffecf9bb26 in llvm::CloneAndPruneFunctionInto(llvm::Function*, llvm::Function const*, llvm::ValueMap<llvm::Value const*, llvm::WeakTrackingVH, llvm::ValueMapConfig<llvm::Value const*, llvm::sys::SmartMutex<false> > >&, bool, llvm::SmallVectorImpl<llvm::ReturnInst*>&, char const*, llvm::ClonedCodeInfo*, llvm::Instruction*) () from /lib/x86_64-linux-gnu/libLLVM-9.so.1
#7  0x00007fffecfb63f4 in llvm::InlineFunction(llvm::CallSite, llvm::InlineFunctionInfo&, llvm::AAResults*, bool, llvm::Function*) () from /lib/x86_64-linux-gnu/libLLVM-9.so.1
#8  0x00007fffed379bb3 in llvm::LegacyInlinerBase::inlineCalls(llvm::CallGraphSCC&) () from /lib/x86_64-linux-gnu/libLLVM-9.so.1
#9  0x00007fffed4bf42f in ?? () from /lib/x86_64-linux-gnu/libLLVM-9.so.1
#10 0x00007fffec9419f0 in llvm::legacy::PassManagerImpl::run(llvm::Module&) () from /lib/x86_64-linux-gnu/libLLVM-9.so.1
#11 0x00007fffe87b918b in ?? () from /lib/x86_64-linux-gnu/libigc.so.1
#12 0x00007fffe87b9623 in ?? () from /lib/x86_64-linux-gnu/libigc.so.1
#13 0x00007fffe8779616 in ?? () from /lib/x86_64-linux-gnu/libigc.so.1
#14 0x00007fffe8848165 in ?? () from /lib/x86_64-linux-gnu/libigc.so.1
#15 0x00007ffff78c5a07 in ?? () from /usr/lib/x86_64-linux-gnu/intel-opencl/libigdrcl.so
#16 0x00007ffff79219a8 in ?? () from /usr/lib/x86_64-linux-gnu/intel-opencl/libigdrcl.so
#17 0x00007ffff788bc99 in ?? () from /usr/lib/x86_64-linux-gnu/intel-opencl/libigdrcl.so
#18 0x0000555555555760 in main (argc=1, argv=0x7fffffffdce8) at src/main.cpp:77
```

**Comment by paigeale** [comment]
As part of a cleanup effort we will be closing this issue. If issue still persists on LLVM 10 please reopen and we will have a developer work with you to try to resolve
