### ISSUE TITLE
ocloc crashes with LLVM 13

### ISSUE THREAD

**Issue by zboszor** [intel/intel-graphics-compiler#204]
I have a (not really usable) backtrace from running ocloc via a qemu wrapper when building under Yocto 3.4 with LLVM 13 from meta-clang.
```
$ cd /data/dtd-yocto-3.4/tmp-sicom-glibc/work/corei7-64-oe-linux/intel-compute-runtime/21.36.20889-r0/git/shared/source/built_ins/kernels
$ PATH=/data/dtd-yocto-3.4/tmp-sicom-glibc/work/corei7-64-oe-linux/intel-compute-runtime/21.36.20889-r0/recipe-sysroot-native/bin:/data/dtd-yocto-3.4/tmp-sicom-glibc/work/corei7-64-oe-linux/intel-compute-runtime/21.36.20889-r0/recipe-sysroot-native/sbin:/data/dtd-yocto-3.4/tmp-sicom-glibc/work/corei7-64-oe-linux/intel-compute-runtime/21.36.20889-r0/recipe-sysroot-native/usr/bin:/data/dtd-yocto-3.4/tmp-sicom-glibc/work/corei7-64-oe-linux/intel-compute-runtime/21.36.20889-r0/recipe-sysroot-native/usr/sbin /data/dtd-yocto-3.4/tmp-sicom-glibc/work/corei7-64-oe-linux/intel-compute-runtime/21.36.20889-r0/qemuwrapper /data/dtd-yocto-3.4/tmp-sicom-glibc/work/corei7-64-oe-linux/intel-compute-runtime/21.36.20889-r0/build/bin/ocloc -q -file /data/dtd-yocto-3.4/tmp-sicom-glibc/work/corei7-64-oe-linux/intel-compute-runtime/21.36.20889-r0/build/bin/built_ins/x64/gen12lp/bindful_copy_buffer_to_buffer_stateless_Gen12LPlp.spv -spirv_input -device tgllp -cl-intel-greater-than-4GB-buffer-required -64 -output bindful_copy_buffer_to_buffer_stateless_0 -out_dir /data/dtd-yocto-3.4/tmp-sicom-glibc/work/corei7-64-oe-linux/intel-compute-runtime/21.36.20889-r0/build/bin/built_ins/x64/gen12lp -revision_id 0 -options -cl-kernel-arg-info
[0]: /data/dtd-yocto-3.4/tmp-sicom-glibc/work/corei7-64-oe-linux/intel-compute-runtime/21.36.20889-r0/build/bin/libocloc.so(+0x7f3f0) [0x40018bb3f0]
[1]: /data/dtd-yocto-3.4/tmp-sicom-glibc/work/corei7-64-oe-linux/intel-compute-runtime/21.36.20889-r0/recipe-sysroot/usr/lib/libc.so.6(+0x41930) [0x400193e930]
[2]: /data/dtd-yocto-3.4/tmp-sicom-glibc/work/corei7-64-oe-linux/intel-compute-runtime/21.36.20889-r0/recipe-sysroot/usr/lib/libLLVM-13.so(_ZN4llvm11PointerType3getEPNS_4TypeEj+0x20) [0x40048009a0]
[3]: /data/dtd-yocto-3.4/tmp-sicom-glibc/work/corei7-64-oe-linux/intel-compute-runtime/21.36.20889-r0/recipe-sysroot/usr/lib/libigc.so.1(+0x2b20e5) [0x40020b90e5]
[4]: /data/dtd-yocto-3.4/tmp-sicom-glibc/work/corei7-64-oe-linux/intel-compute-runtime/21.36.20889-r0/recipe-sysroot/usr/lib/libigc.so.1(+0x2cf642) [0x40020d6642]
[5]: /data/dtd-yocto-3.4/tmp-sicom-glibc/work/corei7-64-oe-linux/intel-compute-runtime/21.36.20889-r0/recipe-sysroot/usr/lib/libigc.so.1(+0x2d2b11) [0x40020d9b11]
[6]: /data/dtd-yocto-3.4/tmp-sicom-glibc/work/corei7-64-oe-linux/intel-compute-runtime/21.36.20889-r0/recipe-sysroot/usr/lib/libigc.so.1(+0x2d8588) [0x40020df588]
[7]: /data/dtd-yocto-3.4/tmp-sicom-glibc/work/corei7-64-oe-linux/intel-compute-runtime/21.36.20889-r0/recipe-sysroot/usr/lib/libigc.so.1(+0x2ddf9f) [0x40020e4f9f]
[8]: /data/dtd-yocto-3.4/tmp-sicom-glibc/work/corei7-64-oe-linux/intel-compute-runtime/21.36.20889-r0/recipe-sysroot/usr/lib/libigc.so.1(+0x2dea98) [0x40020e5a98]
[9]: /data/dtd-yocto-3.4/tmp-sicom-glibc/work/corei7-64-oe-linux/intel-compute-runtime/21.36.20889-r0/recipe-sysroot/usr/lib/libigc.so.1(+0x219d78) [0x4002020d78]
[10]: /data/dtd-yocto-3.4/tmp-sicom-glibc/work/corei7-64-oe-linux/intel-compute-runtime/21.36.20889-r0/recipe-sysroot/usr/lib/libigc.so.1(+0x21cada) [0x4002023ada]
[11]: /data/dtd-yocto-3.4/tmp-sicom-glibc/work/corei7-64-oe-linux/intel-compute-runtime/21.36.20889-r0/recipe-sysroot/usr/lib/libigc.so.1(+0x21ddaa) [0x4002024daa]
[12]: /data/dtd-yocto-3.4/tmp-sicom-glibc/work/corei7-64-oe-linux/intel-compute-runtime/21.36.20889-r0/recipe-sysroot/usr/lib/libigc.so.1(+0x2ec6ee) [0x40020f36ee]
[13]: /data/dtd-yocto-3.4/tmp-sicom-glibc/work/corei7-64-oe-linux/intel-compute-runtime/21.36.20889-r0/recipe-sysroot/usr/lib/libigc.so.1(+0x2ed59f) [0x40020f459f]
[14]: /data/dtd-yocto-3.4/tmp-sicom-glibc/work/corei7-64-oe-linux/intel-compute-runtime/21.36.20889-r0/build/bin/libocloc.so(_ZN3NEO15OfflineCompiler15buildSourceCodeEv+0x23b) [0x400188e3db]
[15]: /data/dtd-yocto-3.4/tmp-sicom-glibc/work/corei7-64-oe-linux/intel-compute-runtime/21.36.20889-r0/build/bin/libocloc.so(_ZN3NEO15OfflineCompiler5buildEv+0x45) [0x4001892e15]
[16]: /data/dtd-yocto-3.4/tmp-sicom-glibc/work/corei7-64-oe-linux/intel-compute-runtime/21.36.20889-r0/build/bin/libocloc.so(+0x7f499) [0x40018bb499]
[17]: /data/dtd-yocto-3.4/tmp-sicom-glibc/work/corei7-64-oe-linux/intel-compute-runtime/21.36.20889-r0/build/bin/libocloc.so(_Z20buildWithSafetyGuardPN3NEO15OfflineCompilerE+0xba) [0x40018bb34a]
[18]: /data/dtd-yocto-3.4/tmp-sicom-glibc/work/corei7-64-oe-linux/intel-compute-runtime/21.36.20889-r0/build/bin/libocloc.so(oclocInvoke+0xc3b) [0x400187e5eb]
[19]: /data/dtd-yocto-3.4/tmp-sicom-glibc/work/corei7-64-oe-linux/intel-compute-runtime/21.36.20889-r0/build/bin/ocloc(main+0x23) [0x4000000753]
[20]: /data/dtd-yocto-3.4/tmp-sicom-glibc/work/corei7-64-oe-linux/intel-compute-runtime/21.36.20889-r0/recipe-sysroot/usr/lib/libc.so.6(+0x2d51b) [0x400192a51b]
[21]: /data/dtd-yocto-3.4/tmp-sicom-glibc/work/corei7-64-oe-linux/intel-compute-runtime/21.36.20889-r0/recipe-sysroot/usr/lib/libc.so.6(__libc_start_main+0x7c) [0x400192a5cc]
[22]: /data/dtd-yocto-3.4/tmp-sicom-glibc/work/corei7-64-oe-linux/intel-compute-runtime/21.36.20889-r0/build/bin/ocloc(_start+0x25) [0x4000000785]
qemu: uncaught target signal 6 (Aborted) - core dumped
/data/dtd-yocto-3.4/tmp-sicom-glibc/work/corei7-64-oe-linux/intel-compute-runtime/21.36.20889-r0/qemuwrapper: line 2: 3885868 Aborted                 (core dumped) PSEUDO_UNLOAD=1 qemu-x86_64 -r 3.2.0 -cpu Nehalem,check=false -L /data/dtd-yocto-3.4/tmp-sicom-glibc/work/corei7-64-oe-linux/intel-compute-runtime/21.36.20889-r0/recipe-sysroot -E LD_LIBRARY_PATH=/data/dtd-yocto-3.4/tmp-sicom-glibc/work/corei7-64-oe-linux/intel-compute-runtime/21.36.20889-r0/build/bin:/data/dtd-yocto-3.4/tmp-sicom-glibc/work/corei7-64-oe-linux/intel-compute-runtime/21.36.20889-r0/recipe-sysroot/usr/lib:/data/dtd-yocto-3.4/tmp-sicom-glibc/work/corei7-64-oe-linux/intel-compute-runtime/21.36.20889-r0/recipe-sysroot/usr/lib "$@"
```
Currently I can only build the latest IGC+compute-runtime via a forked meta-intel Yocto layer if I use `-DNEO_DISABLE_BUILTINS_COMPILATION=1` with LLVM 13.

**Comment by pszymich** [comment]
Hi @zboszor,
I've put your issue on hold in the LLVM 13 support project. When we unclog VectorCompiler build I will look into this.

Please note `build_ubuntu.md` doc is slightly out-of-date with refactor coming; for current up-to-date LLVM version support information please visit our projects page: https://github.com/intel/intel-graphics-compiler/projects.

**Comment by foutrelis** [comment]
Wonder if this ASan provides any clues as to what the issue might be:

```
==908==ERROR: AddressSanitizer: new-delete-type-mismatch on 0x60300007f930 in thread T0:
  object passed to delete has wrong type:
  size of the allocated type:   28 bytes;
  size of the deallocated type: 24 bytes.
    #0 0x55630c21d6a9 in operator delete(void*, unsigned long) (/build/intel-compute-runtime/src/build/bin/ocloc+0x1036a9)
    #1 0x7ff2365c0c83 in std::default_delete<iOpenCL::PointerInputAnnotation>::operator()(iOpenCL::PointerInputAnnotation*) const /usr/include/c++/11.1.0/bits/unique_ptr.h:85:2
    #2 0x7ff2365c0c83 in std::unique_ptr<iOpenCL::PointerInputAnnotation, std::default_delete<iOpenCL::PointerInputAnnotation> >::~unique_ptr() /usr/include/c++/11.1.0/bits/unique_ptr.h:361:17
    #3 0x7ff2365c0c83 in void std::_Destroy<std::unique_ptr<iOpenCL::PointerInputAnnotation, std::default_delete<iOpenCL::PointerInputAnnotation> > >(std::unique_ptr<iOpenCL::PointerInputAnnotation, std::default_delete<iOpenCL::PointerInputAnnotation> >*) /usr/include/c++/11.1.0/bits/stl_construct.h:140:22
    #4 0x7ff2365c0c83 in void std::_Destroy_aux<false>::__destroy<std::unique_ptr<iOpenCL::PointerInputAnnotation, std::default_delete<iOpenCL::PointerInputAnnotation> >*>(std::unique_ptr<iOpenCL::PointerInputAnnotation, std::default_delete<iOpenCL::PointerInputAnnotation> >*, std::unique_ptr<iOpenCL::PointerInputAnnotation, std::default_delete<iOpenCL::PointerInputAnnotation> >*) /usr/include/c++/11.1.0/bits/stl_construct.h:152:19
    #5 0x7ff2365c0c83 in void std::_Destroy<std::unique_ptr<iOpenCL::PointerInputAnnotation, std::default_delete<iOpenCL::PointerInputAnnotation> >*>(std::unique_ptr<iOpenCL::PointerInputAnnotation, std::default_delete<iOpenCL::PointerInputAnnotation> >*, std::unique_ptr<iOpenCL::PointerInputAnnotation, std::default_delete<iOpenCL::PointerInputAnnotation> >*) /usr/include/c++/11.1.0/bits/stl_construct.h:185:11
    #6 0x7ff2365c0c83 in void std::_Destroy<std::unique_ptr<iOpenCL::PointerInputAnnotation, std::default_delete<iOpenCL::PointerInputAnnotation> >*, std::unique_ptr<iOpenCL::PointerInputAnnotation, std::default_delete<iOpenCL::PointerInputAnnotation> > >(std::unique_ptr<iOpenCL::PointerInputAnnotation, std::default_delete<iOpenCL::PointerInputAnnotation> >*, std::unique_ptr<iOpenCL::PointerInputAnnotation, std::default_delete<iOpenCL::PointerInputAnnotation> >*, std::allocator<std::unique_ptr<iOpenCL::PointerInputAnnotation, std::default_delete<iOpenCL::PointerInputAnnotation> > >&) /usr/include/c++/11.1.0/bits/alloc_traits.h:746:15
    #7 0x7ff2365c0c83 in std::vector<std::unique_ptr<iOpenCL::PointerInputAnnotation, std::default_delete<iOpenCL::PointerInputAnnotation> >, std::allocator<std::unique_ptr<iOpenCL::PointerInputAnnotation, std::default_delete<iOpenCL::PointerInputAnnotation> > > >::_M_erase_at_end(std::unique_ptr<iOpenCL::PointerInputAnnotation, std::default_delete<iOpenCL::PointerInputAnnotation> >*) /usr/include/c++/11.1.0/bits/stl_vector.h:1796:19
    #8 0x7ff2365c0c83 in std::vector<std::unique_ptr<iOpenCL::PointerInputAnnotation, std::default_delete<iOpenCL::PointerInputAnnotation> >, std::allocator<std::unique_ptr<iOpenCL::PointerInputAnnotation, std::default_delete<iOpenCL::PointerInputAnnotation> > > >::clear() /usr/include/c++/11.1.0/bits/stl_vector.h:1499:24
    #9 0x7ff2365c0c83 in IGC::COpenCLKernel::ClearKernelInfo() /usr/src/debug/intel-graphics-compiler-igc-1.0.8744/IGC/Compiler/CISACodeGen/OpenCLKernelCodeGen.cpp:73:42
    #10 0x7ff2365c0fd7 in IGC::COpenCLKernel::~COpenCLKernel() /usr/src/debug/intel-graphics-compiler-igc-1.0.8744/IGC/Compiler/CISACodeGen/OpenCLKernelCodeGen.cpp:63:24
    #11 0x7ff2365c1078 in IGC::COpenCLKernel::~COpenCLKernel() /usr/src/debug/intel-graphics-compiler-igc-1.0.8744/IGC/Compiler/CISACodeGen/OpenCLKernelCodeGen.cpp:65:5
    #12 0x7ff236574f8d in IGC::CShaderProgram::~CShaderProgram() /usr/src/debug/intel-graphics-compiler-igc-1.0.8744/IGC/Compiler/CISACodeGen/CShader.cpp:3610:16
    #13 0x7ff2364958e0 in iOpenCL::CGen8OpenCLProgram::~CGen8OpenCLProgram() /usr/src/debug/intel-graphics-compiler-igc-1.0.8744/IGC/AdaptorOCL/OCL/sp/spp_g8.cpp:134:16
    #14 0x7ff23647b37d in IGC::OpenCLProgramContext::~OpenCLProgramContext() /usr/src/debug/intel-graphics-compiler-igc-1.0.8744/IGC/Compiler/CodeGenPublic.h:1266:11
    #15 0x7ff23647b37d in TC::TranslateBuild(TC::STB_TranslateInputArgs const*, TC::STB_TranslateOutputArgs*, TC::TB_DATA_FORMAT, IGC::CPlatform const&, float) /usr/src/debug/intel-graphics-compiler-igc-1.0.8744/IGC/AdaptorOCL/dllInterfaceCompute.cpp:1308:1
    #16 0x7ff23654d7b6 in IGC::IgcOclTranslationCtx<0ul>::Impl::Translate(unsigned long, CIF::Builtins::Buffer<1ul>*, CIF::Builtins::Buffer<1ul>*, CIF::Builtins::Buffer<1ul>*, CIF::Builtins::Buffer<1ul>*, CIF::Builtins::Buffer<1ul>*, CIF::Builtins::Buffer<1ul>*, unsigned int, void*) const /usr/src/debug/intel-graphics-compiler-igc-1.0.8744/IGC/AdaptorOCL/ocl_igc_interface/impl/igc_ocl_translation_ctx_impl.h:282:45
    #17 0x7ff23654e68e in IGC::IgcOclTranslationCtx<1ul>::TranslateImpl(unsigned long, CIF::Builtins::Buffer<1ul>*, CIF::Builtins::Buffer<1ul>*, CIF::Builtins::Buffer<1ul>*, CIF::Builtins::Buffer<1ul>*, unsigned int) /usr/src/debug/intel-graphics-compiler-igc-1.0.8744/IGC/AdaptorOCL/ocl_igc_interface/impl/igc_ocl_translation_ctx_impl.cpp:23:38
    #18 0x7ff2398c7635 in std::unique_ptr<IGC::OclTranslationOutput<1ul>, CIF::RAII::ReleaseHelper<IGC::OclTranslationOutput<1ul> > > IGC::IgcOclTranslationCtx<1ul>::Translate<IGC::OclTranslationOutput<1ul> >(CIF::Builtins::Buffer<1ul>*, CIF::Builtins::Buffer<1ul>*, CIF::Builtins::Buffer<1ul>*, CIF::Builtins::Buffer<1ul>*, unsigned int) /usr/include/igc/ocl_igc_interface/igc_ocl_translation_ctx.h:38:16
    #19 0x7ff2398c7635 in NEO::OfflineCompiler::buildSourceCode() /build/intel-compute-runtime/src/compute-runtime-21.44.21506/shared/offline_compiler/source/offline_compiler.cpp:266:44
    #20 0x7ff2398c88a4 in NEO::OfflineCompiler::build() /build/intel-compute-runtime/src/compute-runtime-21.44.21506/shared/offline_compiler/source/offline_compiler.cpp:293:18
    #21 0x7ff2399f1cf1 in int SafetyGuardLinux::call<int, NEO::OfflineCompiler, int (NEO::OfflineCompiler::*)()>(NEO::OfflineCompiler*, int (NEO::OfflineCompiler::*)(), int) /build/intel-compute-runtime/src/compute-runtime-21.44.21506/shared/offline_compiler/source/utilities/linux/safety_guard_linux.h:62:20
    #22 0x7ff2399f1aa4 in buildWithSafetyGuard(NEO::OfflineCompiler*) /build/intel-compute-runtime/src/compute-runtime-21.44.21506/shared/offline_compiler/source/utilities/linux/safety_caller_linux.cpp:18:24
    #23 0x7ff239875b12 in oclocInvoke /build/intel-compute-runtime/src/compute-runtime-21.44.21506/shared/offline_compiler/source/ocloc_api.cpp:132:26
    #24 0x55630c21f5bb in main /build/intel-compute-runtime/src/compute-runtime-21.44.21506/shared/offline_compiler/source/main.cpp:11:12
    #25 0x7ff239266b24 in __libc_start_main (/usr/lib/libc.so.6+0x27b24)
    #26 0x55630c13b19d in _start (/build/intel-compute-runtime/src/build/bin/ocloc+0x2119d)

0x60300007f930 is located 0 bytes inside of 28-byte region [0x60300007f930,0x60300007f94c)
allocated by thread T0 here:
    #0 0x55630c21c7c9 in operator new(unsigned long) (/build/intel-compute-runtime/src/build/bin/ocloc+0x1027c9)
    #1 0x7ff2365cad8e in std::_MakeUniq<iOpenCL::PrivateInputAnnotation>::__single_object std::make_unique<iOpenCL::PrivateInputAnnotation>() /usr/include/c++/11.1.0/bits/unique_ptr.h:962:30
    #2 0x7ff2365cad8e in IGC::COpenCLKernel::CreateAnnotations(IGC::KernelArg*, unsigned int) /usr/src/debug/intel-graphics-compiler-igc-1.0.8744/IGC/Compiler/CISACodeGen/OpenCLKernelCodeGen.cpp:1013:84
    #3 0x7ff2365cbef7 in IGC::COpenCLKernel::AllocatePayload() /usr/src/debug/intel-graphics-compiler-igc-1.0.8744/IGC/Compiler/CISACodeGen/OpenCLKernelCodeGen.cpp:1712:34
    #4 0x7ff2367c08a8 in IGC::EmitPass::runOnFunction(llvm::Function&) /usr/src/debug/intel-graphics-compiler-igc-1.0.8744/IGC/Compiler/CISACodeGen/EmitVISAPass.cpp:1014:42
    #5 0x7ff2303678ff in llvm::FPPassManager::runOnFunction(llvm::Function&) (/usr/lib/libLLVM-13.so+0xd058ff)

SUMMARY: AddressSanitizer: new-delete-type-mismatch (/build/intel-compute-runtime/src/build/bin/ocloc+0x1036a9) in operator delete(void*, unsigned long)
```

**Comment by eero-t** [comment]
What are the versions of the dependencies other than LLVM?

Why the build is done under (x86_64) Qemu, and what additional limitations (e.g. RAM) it sets on the build environment?

Can you reproduce ocloc crash without Qemu (e.g. in a docker container, if you want build to be isolated)?

**Comment by zboszor** [comment]
> What are the versions of the dependencies other than LLVM?

The versions are in the honister and current master branches of Yocto's openembedded-core, meta-openembedded, meta-clang and meta-intel.

> Why the build is done under (x86_64) Qemu, and what additional limitations (e.g. RAM) it sets on the build environment?

Because in a cross-compiling environment (e.g. Yocto) you have two ways to deal with executables built and run during the build: either use a host-native build variant and use the executables from that (which does not work if the executable relies on type sizes and the host and target are different), or use a Qemu wrapper (e.g. with `-DCMAKE_CROSSCOMPILING_EMULATOR=...` and just do the complete build for the target  architecture.

As far as I know, the qemu-native build Yocto uses for this purpose doesn't limit RAM, it simply allocates from the host system as needed. The target binaries are run just like any regular user-space binary only via the CPU emulator.

> 
> Can you reproduce ocloc crash without Qemu (e.g. in a docker container, if you want build to be isolated)?

According to the above Arch Linux commits, the answer is yes.

**Comment by zboszor** [comment]
> Traced it to [llvm/llvm-project@b00cff5](https://github.com/llvm/llvm-project/commit/b00cff56cfb15cbfa74cb512c9cee1c402cce55b) and verified that reverting that commit on top of LLVM 13.0.0 avoids the ocloc crash.
> 
> It seems that IGC should not pass `nullptr` to "GetElementPtrInst::Create() (and IRBuilder methods based on it)" in order to work with LLVM 13.

And here's the reasoning from LLVM devs: https://reviews.llvm.org/D105653?id=357321

> 
> Edit: The above allowed me to remove `NEO_DISABLE_BUILTINS_COMPILATION=ON` but when dropping `SKIP_UNIT_TESTS=1` as well, I get a different ocloc crash:
> 
> Edit 2: Digging further into the second crash, it appears to crash [here](https://github.com/intel/intel-graphics-compiler/commit/0d561cc954841e5eadc4c60398e8a8207c25110b#diff-2084e0fd4cf7c1af0b2be093421d8df19f4c771ba0a41210d1c0eb2bb4e8a012R29) because `T` is null. The `TargetRegistry::lookupTarget` call sets Err to `No available targets are compatible with triple "vISA_64"`.

**Comment by zboszor** [comment]
> Edit 2: Digging further into the second crash, it appears to crash [here](https://github.com/intel/intel-graphics-compiler/commit/0d561cc954841e5eadc4c60398e8a8207c25110b#diff-2084e0fd4cf7c1af0b2be093421d8df19f4c771ba0a41210d1c0eb2bb4e8a012R29) because `T` is null. The `TargetRegistry::lookupTarget` call sets Err to `No available targets are compatible with triple "vISA_64"`.

IGC calls `TargetRegistry::RegisterTarget()` twice in `IGC/VectorCompiler/lib/GenXCodeGen/TargetInfo/GenXTargetInfo.cpp` with target/backend names `"genx32"` and `"genx64"`, respectively, but doesn't provide the function for the 5th argument `Target::ArchMatchFnTy ArchMatchFn` so VISAModule::m_triple == "vISA_64" can't be matched as a compatible machine triple.

Alternatively, the "machine triple" setting:
```
./IGC/DebugInfo/VISAModule.hpp:356:        std::string m_triple = "vISA_64";
```
should be `std::string m_triple = "genx64";` instead.

**Comment by zboszor** [comment]
LLVM 14 was also released.

**Comment by frantisekz** [comment]
@pszymich sorry for plainly asking, is this planned to be worked on? Do you have any rough estimates? Unfortunately, reverting the offending LLVM 13 change is a no go for Fedora, so compute-runtime support in Fedora depends on this issue.

**Comment by jike212** [comment]
Just wanted to echo @frantisekz to see if there might be a timeline for resolution on this. It would be great to see this in time for Fedora 36 particularly given that large hardware vendors like Lenovo offer Fedora as a supported OS installed out of the box.

**Comment by janhenke** [comment]
Gentoo also removed LLVM 11 from the distribution this week and LLVM 13 is the current default version. This bug has hit multiple users (including myself). It would be rather important to get this one fixed, as even a plain `clinfo` call leads to a segfault now. Downstream bug: https://bugs.gentoo.org/837872

**Comment by eero-t** [comment]
@janhenke Is there a problem also with LLVM 12, or does it work as intermediate solution?

It's marked as working, but not tested by compute-runtime project as well as LLVM 11: https://github.com/intel/intel-graphics-compiler/projects/2

In my own light testing of my own LLVM 12 build, it worked OK too.

**Comment by janhenke** [comment]
We jumped directly from 11 to 13, so I do not have any test results from 12. As well as some parts of the stack based on LLVM also got removed already. Anyway getting it to work on 13 is rather urgent, as some distributions are following LLVM releases rather closely and keep at most 2-3 releases in their repos (Gentoo is already working towards removing LLVM 12 as said above).

**Comment by rathann** [comment]
FWIW, LLVM 14 is already in the soon-to-be-released Fedora 36.

**Comment by eero-t** [comment]
> We jumped directly from 11 to 13
> ...
> some distributions are following LLVM releases rather closely and keep at most 2-3 releases in their repos

I wonder whether it makes sense for compute-runtime to skip every other LLVM release, and concentrate support only e.g. to odd numbered LLVM releases (11, 13, 15...).   Any comments on this from the distro perspective, and from compute-runtime developers?

**Comment by rathann** [comment]
From Fedora perspective, we are tracking the latest LLVM releases. While it's possible to maintain a compatibility package with the previous version, having the compute-runtime link against older version might cause trouble if the application using it is linked against the latest LLVM libraries (i.e. you get two different LLVM runtimes loaded in the same process).

**Comment by jbeich** [comment]
> from the distro perspective

May not help as each distro has different update cadence. For example, LTO in Firefox requires LLVM bundled in Rust compiler to match Clang version. As of Firefox 101 this means Rust 1.60 (LLVM 14), see https://bugzilla.mozilla.org/show_bug.cgi?id=1758780

On FreeBSD we support LLVM back to 8.0.1, so IGC as a downstream package exist for both LLVM 11 and LLVM 12. While IGC claims to support LLVM < 11 in practice it's a minefield of bugs due to relying on LLVM patches. NixPkgs and Gentoo are more flexible than FreeBSD but it looks like Gentoo dropped the ball with LLVM package(s).

Ideally, IGC package should use bundled LLVM linked statically (a la Rust compiler). Not only it'd help with LLVM package proliferation but also ensure downstream QA matches upstream QA.

**Comment by ConiKost** [comment]
In Gentoo, we have an approch of slotted versions, which means, someone can install independently multiple major versions of LLVM and Clang, which all can co-exist. But maintainers will drop older version. We currently have LLVM12 as lowest version, but in future, this one will be dropped.. LLVM11 just got dropped two weeks ago. So LLVM13 support would be very appreciated.

**Comment by anujm1** [comment]
I don't see this with the latest commits on master. Perhaps fixed by https://github.com/intel/intel-graphics-compiler/commit/73a32f051a881fa89822e888221ec2bfea31f730 and https://github.com/intel/intel-graphics-compiler/commit/84e9ea6e0cb70bb9468fa86003b89f84ddf67997 ?

**Comment by zboszor** [comment]
> I don't see this with the latest commits on master. Perhaps fixed by [73a32f0](https://github.com/intel/intel-graphics-compiler/commit/73a32f051a881fa89822e888221ec2bfea31f730) and [84e9ea6](https://github.com/intel/intel-graphics-compiler/commit/84e9ea6e0cb70bb9468fa86003b89f84ddf67997) ?

It certainly seems so. There is no tagged release yet containing those commits, though.
Hopefully it will work with LLVM 14.0.x and 15, too.

**Comment by pszymich** [comment]
Fixed in latest commits, closing.
