### ISSUE TITLE
Guidence for building igc on virtual box 

### ISSUE THREAD

**Issue by aabhinavg** [intel/intel-graphics-compiler#294]
https://github.com/intel/intel-graphics-compiler/tree/master/scripts
I am using the script [buildIGC.sh](https://github.com/intel/intel-graphics-compiler/blob/master/scripts/buildIGC.sh)

Can anyone guide me on how to use it for a smooth build process if I want to build it on virtual box.

**Comment by pszymich** [comment]
Hi @aabhinavg, what problems did you come across?
Please have a look at our [`build_ubuntu.md`](https://github.com/intel/intel-graphics-compiler/blob/master/documentation/build_ubuntu.md) document.

**Comment by aabhinavg** [comment]
I am getting error while running make command 

as ] Built target obj.clangFrontend
[ 40%] Generating ../Release/GenIntrinsicDescription.h, ../Release/GenIntrinsicDefinition.h, ../Release/GenIntrinsicEnum.h, ../Release/GenIntrinsicLookupTable.h, ../Release/GenIntrinsicDefinition.cpp
Traceback (most recent call last):
  File "generate_intrinsic_files.py", line 29, in <module>
    main(sys.argv)
  File "generate_intrinsic_files.py", line 26, in main
    intrinsic_definitions = generate_type_definitions_from_modules(args.inputs)
  File "/home/ht/workspace/igc/IGC/GenISAIntrinsics/generator/Intrinsic_definition_translation.py", line 135, in generate_type_definitions_from_modules
    spec = importlib.util.spec_from_file_location(Path(el).stem, el)
AttributeError: module 'importlib' has no attribute 'util'
make[2]: *** [IGC/GenISAIntrinsics/CMakeFiles/GenISAIntrinsics.dir/build.make:84: IGC/Release/GenIntrinsicDescription.h] Error 1
make[1]: *** [CMakeFiles/Makefile2:33579: IGC/GenISAIntrinsics/CMakeFiles/GenISAIntrinsics.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
] Built target obj.clangFrontend
[ 40%] Generating ../Release/GenIntrinsicDescription.h, ../Release/GenIntrinsicDefinition.h, ../Release/GenIntrinsicEnum.h, ../Release/GenIntrinsicLookupTable.h, ../Release/GenIntrinsicDefinition.cpp
Traceback (most recent call last):
  File "generate_intrinsic_files.py", line 29, in <module>
    main(sys.argv)
  File "generate_intrinsic_files.py", line 26, in main
    intrinsic_definitions = generate_type_definitions_from_modules(args.inputs)
  File "/home/ht/workspace/igc/IGC/GenISAIntrinsics/generator/Intrinsic_definition_translation.py", line 135, in generate_type_definitions_from_modules
    spec = importlib.util.spec_from_file_location(Path(el).stem, el)
AttributeError: module 'importlib' has no attribute 'util'
make[2]: *** [IGC/GenISAIntrinsics/CMakeFiles/GenISAIntrinsics.dir/build.make:84: IGC/Release/GenIntrinsicDescription.h] Error 1
make[1]: *** [CMakeFiles/Makefile2:33579: IGC/GenISAIntrinsics/CMakeFiles/GenISAIntrinsics.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....



I have followed the steps shown in the[build_ubuntu.md](https://github.com/intel/intel-graphics-compiler/blob/master/documentation/build_ubuntu.md)

**Comment by aabhinavg** [comment]
HI @pszymich  I was able to solve the build issue by doing some modification in the python code.
I am following the  [build_ubuntu.md](https://github.com/intel/intel-graphics-compiler/blob/master/documentation/build_ubuntu.md)
directory hirerachy.
Inside workspace i have cloned everythings
workspace
mkdir build
cd build
cmake ../igc
make -j `nproc`
sudo make install

Till here i dont got any error 
But  now I am not able to see the igc binaries.
Where they are located and how to use the igc compiler can you share some documentation or step.?

**Comment by pszymich** [comment]
IGC can be invoked by compute-runtime (https://github.com/intel/compute-runtime) or the `ocloc` tool that is a part of the runtime binaries.
`make install` should compile, link and install IGC, the binaries should be in the `build` directory.
Please reopen or file a new issue if you experience further problems, thank you.
